class_name FlagData
## Country codes, names, and texture loading for nationality flags.
## Flag SVGs from Neon Patrol project (assets/icons/flags/*.svg).

const COUNTRIES: Array = [
	{"code": "AD", "name": "Andorra"},
	{"code": "AE", "name": "UAE"},
	{"code": "AF", "name": "Afghanistan"},
	{"code": "AG", "name": "Antigua & Barbuda"},
	{"code": "AL", "name": "Albania"},
	{"code": "AM", "name": "Armenia"},
	{"code": "AO", "name": "Angola"},
	{"code": "AR", "name": "Argentina"},
	{"code": "AT", "name": "Austria"},
	{"code": "AU", "name": "Australia"},
	{"code": "AZ", "name": "Azerbaijan"},
	{"code": "BA", "name": "Bosnia"},
	{"code": "BB", "name": "Barbados"},
	{"code": "BD", "name": "Bangladesh"},
	{"code": "BE", "name": "Belgium"},
	{"code": "BF", "name": "Burkina Faso"},
	{"code": "BG", "name": "Bulgaria"},
	{"code": "BH", "name": "Bahrain"},
	{"code": "BI", "name": "Burundi"},
	{"code": "BJ", "name": "Benin"},
	{"code": "BN", "name": "Brunei"},
	{"code": "BO", "name": "Bolivia"},
	{"code": "BR", "name": "Brazil"},
	{"code": "BS", "name": "Bahamas"},
	{"code": "BT", "name": "Bhutan"},
	{"code": "BW", "name": "Botswana"},
	{"code": "BY", "name": "Belarus"},
	{"code": "BZ", "name": "Belize"},
	{"code": "CA", "name": "Canada"},
	{"code": "CD", "name": "DR Congo"},
	{"code": "CF", "name": "Central African Rep."},
	{"code": "CG", "name": "Congo"},
	{"code": "CH", "name": "Switzerland"},
	{"code": "CI", "name": "Ivory Coast"},
	{"code": "CL", "name": "Chile"},
	{"code": "CM", "name": "Cameroon"},
	{"code": "CN", "name": "China"},
	{"code": "CO", "name": "Colombia"},
	{"code": "CR", "name": "Costa Rica"},
	{"code": "CU", "name": "Cuba"},
	{"code": "CV", "name": "Cape Verde"},
	{"code": "CY", "name": "Cyprus"},
	{"code": "CZ", "name": "Czechia"},
	{"code": "DE", "name": "Germany"},
	{"code": "DJ", "name": "Djibouti"},
	{"code": "DK", "name": "Denmark"},
	{"code": "DM", "name": "Dominica"},
	{"code": "DO", "name": "Dominican Rep."},
	{"code": "DZ", "name": "Algeria"},
	{"code": "EC", "name": "Ecuador"},
	{"code": "EE", "name": "Estonia"},
	{"code": "EG", "name": "Egypt"},
	{"code": "ER", "name": "Eritrea"},
	{"code": "ES", "name": "Spain"},
	{"code": "ET", "name": "Ethiopia"},
	{"code": "FI", "name": "Finland"},
	{"code": "FJ", "name": "Fiji"},
	{"code": "FR", "name": "France"},
	{"code": "GA", "name": "Gabon"},
	{"code": "GB", "name": "United Kingdom"},
	{"code": "GD", "name": "Grenada"},
	{"code": "GE", "name": "Georgia"},
	{"code": "GH", "name": "Ghana"},
	{"code": "GM", "name": "Gambia"},
	{"code": "GN", "name": "Guinea"},
	{"code": "GQ", "name": "Equatorial Guinea"},
	{"code": "GR", "name": "Greece"},
	{"code": "GT", "name": "Guatemala"},
	{"code": "GW", "name": "Guinea-Bissau"},
	{"code": "GY", "name": "Guyana"},
	{"code": "HN", "name": "Honduras"},
	{"code": "HR", "name": "Croatia"},
	{"code": "HT", "name": "Haiti"},
	{"code": "HU", "name": "Hungary"},
	{"code": "ID", "name": "Indonesia"},
	{"code": "IE", "name": "Ireland"},
	{"code": "IL", "name": "Israel"},
	{"code": "IN", "name": "India"},
	{"code": "IQ", "name": "Iraq"},
	{"code": "IR", "name": "Iran"},
	{"code": "IS", "name": "Iceland"},
	{"code": "IT", "name": "Italy"},
	{"code": "JM", "name": "Jamaica"},
	{"code": "JO", "name": "Jordan"},
	{"code": "JP", "name": "Japan"},
	{"code": "KE", "name": "Kenya"},
	{"code": "KG", "name": "Kyrgyzstan"},
	{"code": "KH", "name": "Cambodia"},
	{"code": "KR", "name": "South Korea"},
	{"code": "KW", "name": "Kuwait"},
	{"code": "KZ", "name": "Kazakhstan"},
	{"code": "LA", "name": "Laos"},
	{"code": "LB", "name": "Lebanon"},
	{"code": "LI", "name": "Liechtenstein"},
	{"code": "LK", "name": "Sri Lanka"},
	{"code": "LR", "name": "Liberia"},
	{"code": "LS", "name": "Lesotho"},
	{"code": "LT", "name": "Lithuania"},
	{"code": "LU", "name": "Luxembourg"},
	{"code": "LV", "name": "Latvia"},
	{"code": "LY", "name": "Libya"},
	{"code": "MA", "name": "Morocco"},
	{"code": "MC", "name": "Monaco"},
	{"code": "MD", "name": "Moldova"},
	{"code": "ME", "name": "Montenegro"},
	{"code": "MG", "name": "Madagascar"},
	{"code": "MK", "name": "North Macedonia"},
	{"code": "ML", "name": "Mali"},
	{"code": "MM", "name": "Myanmar"},
	{"code": "MN", "name": "Mongolia"},
	{"code": "MR", "name": "Mauritania"},
	{"code": "MT", "name": "Malta"},
	{"code": "MU", "name": "Mauritius"},
	{"code": "MV", "name": "Maldives"},
	{"code": "MW", "name": "Malawi"},
	{"code": "MX", "name": "Mexico"},
	{"code": "MY", "name": "Malaysia"},
	{"code": "MZ", "name": "Mozambique"},
	{"code": "NA", "name": "Namibia"},
	{"code": "NE", "name": "Niger"},
	{"code": "NG", "name": "Nigeria"},
	{"code": "NI", "name": "Nicaragua"},
	{"code": "NL", "name": "Netherlands"},
	{"code": "NO", "name": "Norway"},
	{"code": "NP", "name": "Nepal"},
	{"code": "NZ", "name": "New Zealand"},
	{"code": "OM", "name": "Oman"},
	{"code": "PA", "name": "Panama"},
	{"code": "PE", "name": "Peru"},
	{"code": "PG", "name": "Papua New Guinea"},
	{"code": "PH", "name": "Philippines"},
	{"code": "PK", "name": "Pakistan"},
	{"code": "PL", "name": "Poland"},
	{"code": "PT", "name": "Portugal"},
	{"code": "PY", "name": "Paraguay"},
	{"code": "QA", "name": "Qatar"},
	{"code": "RO", "name": "Romania"},
	{"code": "RS", "name": "Serbia"},
	{"code": "RU", "name": "Russia"},
	{"code": "RW", "name": "Rwanda"},
	{"code": "SA", "name": "Saudi Arabia"},
	{"code": "SE", "name": "Sweden"},
	{"code": "SG", "name": "Singapore"},
	{"code": "SI", "name": "Slovenia"},
	{"code": "SK", "name": "Slovakia"},
	{"code": "SN", "name": "Senegal"},
	{"code": "SO", "name": "Somalia"},
	{"code": "TH", "name": "Thailand"},
	{"code": "TN", "name": "Tunisia"},
	{"code": "TR", "name": "Turkey"},
	{"code": "TW", "name": "Taiwan"},
	{"code": "TZ", "name": "Tanzania"},
	{"code": "UA", "name": "Ukraine"},
	{"code": "UG", "name": "Uganda"},
	{"code": "US", "name": "United States"},
	{"code": "UY", "name": "Uruguay"},
	{"code": "UZ", "name": "Uzbekistan"},
	{"code": "VE", "name": "Venezuela"},
	{"code": "VN", "name": "Vietnam"},
	{"code": "ZA", "name": "South Africa"},
	{"code": "ZM", "name": "Zambia"},
	{"code": "ZW", "name": "Zimbabwe"},
]

static var _texture_cache: Dictionary = {}

static func get_flag_texture(code: String) -> Texture2D:
	if code.is_empty():
		return null
	var lower_code := code.to_lower()
	if _texture_cache.has(lower_code):
		return _texture_cache[lower_code]
	var path := "res://assets/icons/flags/%s.svg" % lower_code
	if ResourceLoader.exists(path):
		var tex = load(path)
		_texture_cache[lower_code] = tex
		return tex
	return null

static func get_country_name(code: String) -> String:
	var upper_code := code.to_upper()
	for country in COUNTRIES:
		if country["code"] == upper_code:
			return country["name"]
	return upper_code

static func search_countries(query: String) -> Array:
	if query.is_empty():
		return COUNTRIES.duplicate()
	var q := query.to_lower()
	var results: Array = []
	for country in COUNTRIES:
		if country["code"].to_lower().begins_with(q) or country["name"].to_lower().find(q) >= 0:
			results.append(country)
	return results
